---
title: "Urn Confidence Questionnaire Factor Analysis"
author: "Vickie"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    theme: spacelab
    toc: yes
    toc_float: yes
  html_notebook:
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---
```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = 'center', fig.width = 10, fig.height = 7)
```

```{r}
library(ggplot2) # for plotting graphs
library(tidyverse)
library(data.table)
library(gridExtra) # for ploting graphs
library(lme4) # for linear regression functions
library(plyr) # for collapse-and-mean functions like ddply
library(psych)
library(GPArotation)
library(paran)
library(reshape)
library(polycor)
library(nFactors)
library(R.matlab)
library(reshape)
library(useful)
library(magrittr)
library(corrplot)
library(car)
options(scipen = 999) # to display variable quantities in decimals (not in scientific notation format)
```

## Read in data
```{r}
setwd("/Users/vwang/Documents/PennMed/Gold Lab/Preregistration/Urn-Confidence/UrnConfidenceQuestionnaire/Data/")
q_raw = read_csv("Urn Task Final - Ind_October 8, 2021_06.02.csv")
q_raw = q_raw[-c(1,2),]

taskData = data.table::fread("subjectmeta1010.csv")
combinedData = data.frame()
#IBtable = data.table::fread("IBtable1010.csv")
IBtable = data.table::fread("IBtable1021forgrant.csv")
```

## Check questions
```{r}
check_questions = c("SSMS43_38", "EAT26_18")
check_answers = c("Yes", "Always")
check_answers_numerical = c("2", "6")

q_raw %>% dplyr::select(check_questions)

q_raw %<>% dplyr::select(-check_questions)

q_raw %<>% dplyr::filter(`Prolific ID` %in% taskData$FullSubject) 
```

## Remove first columns
```{r}
rownames = q_raw$`Prolific ID`
q_raw %<>% dplyr::select(contains("_")) %>% sapply(as.numeric) %>% as.data.frame() %>% set_rownames(rownames)
```


```{r}
DASS_raw = q_raw %>% dplyr::select(contains("DASS")) #21
NCS_raw = q_raw %>% dplyr::select(contains("NCS")) #18
SSMS_raw = q_raw %>% dplyr::select(contains("SSMS")) #43
UPPS_raw = q_raw %>% dplyr::select(contains("UPPS")) #20
AUDIT_raw = q_raw %>% dplyr::select(contains("AUDIT")) #10
LSAS_fa_raw = q_raw %>% dplyr::select(contains("LSAS24#1")) #24
LSAS_av_raw = q_raw %>% dplyr::select(contains("LSAS24#2")) #24
OCIR_raw = q_raw %>% dplyr::select(contains("OCIR")) #18
AES_raw = q_raw %>% dplyr::select(contains("AES")) #18
EAT_raw = q_raw %>% dplyr::select(contains("EAT")) #26
```

```{r}
### Higher score more stress, anxiety, depression
DASS_stress = DASS_raw[,c(1,6,8,11,12,14,18)] - 1
DASS_anxiety = DASS_raw[,c(2,4,7,9,15,19,20)] - 1
DASS_depression = DASS_raw[,c(3,5,10,13,16,17,21)] - 1

combinedData <- DASS_stress %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "DASS_stress") %>% rbind(combinedData)
combinedData <- DASS_anxiety %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "DASS_anxiety") %>% rbind(combinedData)
combinedData <- DASS_depression %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "DASS_depression") %>% rbind(combinedData)
```

```{r}
### Higher score more into thinking
reverse_coded_items_NCS = c(3,4,5,7,8,9,12,16,17)
direction_NCS = rep(1,dim(NCS_raw)[2])
direction_NCS[reverse_coded_items_NCS] = -1

NCS = sweep(NCS_raw, MARGIN=2, direction_NCS, `*`) + 4

combinedData <- NCS %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "NCS") %>% rbind(combinedData)
```

```{r}
### Higher score more schizotypy
reverse_coded_items_SSMS = c(26, 27, 28, 30, 31, 34, 37, 39)
direction_SSMS = rep(1,dim(SSMS_raw)[2])
direction_SSMS[reverse_coded_items_SSMS] = -1
add_SSMS = rep(0,dim(SSMS_raw)[2])
add_SSMS[reverse_coded_items_SSMS] = 3

SSMS = sweep(SSMS_raw, MARGIN=2, direction_SSMS, `*`) %>% sweep(MARGIN=2, add_SSMS, `+`) - 1

combinedData <- SSMS %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "SSMS") %>% rbind(combinedData)
```

```{r}
### Higher score more impulsive
reverse_coded_items_UPPS = c(3, 6, 8, 9, 10, 13, 14, 15, 16, 17, 18, 20)
direction_UPPS = rep(-1,dim(UPPS_raw)[2])
direction_UPPS[reverse_coded_items_UPPS] = 1
add_UPPS = rep(5,dim(UPPS_raw)[2])
add_UPPS[reverse_coded_items_UPPS] = 0

UPPS = sweep(UPPS_raw, MARGIN=2, direction_UPPS, `*`) %>% sweep(MARGIN=2, add_UPPS, `+`)

combinedData <- UPPS %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "UPPS") %>% rbind(combinedData)
```


```{r}
different_coded_items_AUDIT = c(9,10)
multiply_AUDIT = rep(1,dim(AUDIT_raw)[2])
multiply_AUDIT[different_coded_items_AUDIT] = 2
add_AUDIT = rep(-1,dim(AUDIT_raw)[2])
add_AUDIT[different_coded_items_AUDIT] = -2

AUDIT = sweep(AUDIT_raw, MARGIN=2, multiply_AUDIT, `*`) %>% sweep(MARGIN=2, add_AUDIT, `+`)

combinedData <- AUDIT %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "AUDIT") %>% rbind(combinedData)
```

```{r}
LSAS = LSAS_av_raw + LSAS_fa_raw - 2

combinedData <- LSAS %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "LSAS") %>% rbind(combinedData)
```

```{r}
OCIR = OCIR_raw - 1

combinedData <- OCIR %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "OCIR") %>% rbind(combinedData)
```

```{r}
reverse_coded_items_AES = c(6,10,11)
direction_AES = rep(-1,dim(AES_raw)[2])
direction_AES[reverse_coded_items_AES] = 1
add_AES = rep(5,dim(AES_raw)[2])
add_AES[reverse_coded_items_AES] = 0

AES = sweep(AES_raw, MARGIN=2, direction_AES, `*`) %>% sweep(MARGIN=2, add_AES, `+`)

combinedData <- AES %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "AES") %>% rbind(combinedData)
```

```{r}
reverse_coded_items_EAT = c(26)
direction_EAT = rep(1,dim(EAT_raw)[2])
direction_EAT[reverse_coded_items_EAT] = -1
add_EAT = rep(-3,dim(EAT_raw)[2])
add_EAT[reverse_coded_items_EAT] = 4

EAT_raw2 = sweep(EAT_raw, MARGIN=2, direction_EAT, `*`) %>% sweep(MARGIN=2, add_EAT, `+`)
EAT = EAT_raw2
EAT[EAT_raw2 < 0] = 0

combinedData <- EAT %>% rownames_to_column(var = "subject") %>% reshape2::melt(id = "subject") %>% dplyr::mutate(survey = "EAT") %>% rbind(combinedData)
```

```{r}
add.one <- function(x, na.rm=FALSE) (x + 1)

#completesubs <- qData[complete.cases(qData),]$subject
summedscaledData <- combinedData %>% #dplyr::filter(subject %in% completesubs) %>%
    cast(subject ~ survey, sum) %>% 
    inner_join(taskData, by = c("subject" = "FullSubject")) %>%
    left_join(IBtable) %>%
    dplyr::mutate_if(is.numeric, add.one) %>%
    dplyr::mutate_if(is.numeric, list(ln = log)) %>%
    dplyr::mutate_if(is.numeric, list(sc = scale)) %>%
    dplyr::mutate(Gender = ifelse(Gender == "Female", 1, 0))

qData <- combinedData %>% cast(subject ~ variable) %>% dplyr::filter(subject %in% summedscaledData$subject)
```

```{r}
regAccuracyDemo = lm(Correct_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 
regConfidenceDemo = lm(Confidence_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 
regIBdtbDemo = lm(DTB_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 
regIBipDemo = lm(Ipast_task_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 
regIBifDemo = lm(Ifuture_task_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 
regIBipbothDemo = lm(Ipast_both_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 
regIBifbothDemo = lm(Ifuture_both_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 
#regIBifratioDemo = lm(ratio_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 
regIBipdiffDemo = lm(pastdiff_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 
regIBifdiffDemo = lm(diff_sc ~ NCS_ln_sc + Age_sc + Gender, summedscaledData) 

regAccuracyDemo_fig <- data.frame(summary(regAccuracyDemo)$coefficients[2:4,1:4]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Accuracy")
regConfidenceDemo_fig <- data.frame(summary(regConfidenceDemo)$coefficients[2:4,1:4]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Confidence")
regIBdtbDemo_fig <- data.frame(summary(regIBdtbDemo)$coefficients[2:4,1:4]) %>% 
    rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "DTB")
regIBipDemo_fig <- data.frame(summary(regIBipDemo)$coefficients[2:4,1:4]) %>% 
    rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ip_task")
regIBifDemo_fig <- data.frame(summary(regIBifDemo)$coefficients[2:4,1:4]) %>% 
    rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "If_task")
regIBipbothDemo_fig <- data.frame(summary(regIBipbothDemo)$coefficients[2:4,1:4]) %>% 
    rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ip_both")
regIBifbothDemo_fig <- data.frame(summary(regIBifbothDemo)$coefficients[2:4,1:4]) %>% 
    rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "If_both")
#regIBifratioDemo_fig <- data.frame(summary(regIBifratioDemo)$coefficients[2:4,1:4]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ifratio")
regIBipdiffDemo_fig <- data.frame(summary(regIBipdiffDemo)$coefficients[2:4,1:4]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ip_diff")
regIBifdiffDemo_fig <- data.frame(summary(regIBifdiffDemo)$coefficients[2:4,1:4]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "If_diff")


regDemo_fig <- rbind(regAccuracyDemo_fig,regConfidenceDemo_fig,
                     regIBdtbDemo_fig,
                     regIBipDemo_fig,regIBifDemo_fig,
                     regIBipbothDemo_fig,regIBifbothDemo_fig,
                     #regIBifratioDemo_fig,
                     regIBipdiffDemo_fig,regIBifdiffDemo_fig)
regDemo_fig <- regDemo_fig[regDemo_fig$Type!='Gender',]
regDemo_fig$Type[regDemo_fig$Type=='NCS_ln_sc']<-'IQ'
regDemo_fig$Type[regDemo_fig$Type=='Age_sc']<-'Age'
regDemo_fig$Label<-factor(regDemo_fig$Label, levels=c("Accuracy",'Confidence',
                                                      "DTB",
                                                      "Ip_task","If_task",
                                                      "Ip_both","If_both",
                                                      #"Ifratio",
                                                      "Ip_diff","If_diff"))


# Plot: Task performance + Metacognition ~ Demographics
demoFig <- ggplot(data = regDemo_fig, aes(x = Label, y = Estimate, group=Type)) + 
  geom_bar(aes(fill = Type), color="black",size=1.2,stat="identity", position = "dodge",width=0.6) +
  geom_errorbar(aes(ymin=regDemo_fig$Estimate-regDemo_fig$Std..Error, ymax=regDemo_fig$Estimate+regDemo_fig$Std..Error),colour="black", width=.3, size=1.2, position=position_dodge(.6)) +
  labs(title=" ", x=" ", y = "Regression Coefficient") + geom_hline(yintercept=0,size=1) + theme_classic() + 
  theme(axis.title.y = element_text(size = 18, angle = 90, margin=margin(0,20,0,0)), axis.title.x = element_text(size = 18, angle = 00, margin=margin(20,0,0,0)))+
  theme(plot.title = element_text(size = 18, angle = 00),legend.text = element_text(size = 18),legend.title = element_blank()) +
  theme(axis.text.x = element_text(angle = 00, size=18), axis.text.y = element_text(angle = 00, size=18))+ scale_x_discrete(expand = c(0,0.5)) +
  theme(axis.line.x = element_line(color="black", size = 1.2), axis.line.y = element_line(color="black", size = 1.2)) +
  theme(axis.ticks.y=element_line(size=(1.5)), axis.ticks.x=element_line(size=(1.5)), axis.ticks.length=unit(0.4, "cm")) +
  scale_fill_manual(values=c("#ffffff", "#555555"))#+ ylim(-0.3,0.4)

demoFig

#pdf("~/Documents/PennMed/Gold Lab/Lab Meeting 10122021/Figs/demoFig.pdf", width = 10, height = 4)
#demoFig
#dev.off()

#pdf("~/Documents/PennMed/Gold Lab/Grant/FigsforGrant/demoFig.pdf", width = 15, height = 4)
demoFig
#dev.off()
```

```{r}
generic.model <- function(DV, df) {
  plot1 <- matrix(NA,10,4)
  modelString = paste(DV, "~ DASS_stress_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[1,] <- summary(mod1)$coefficients[2,1:4]
  
  modelString = paste(DV, "~ DASS_anxiety_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[2,] <- summary(mod1)$coefficients[2,1:4]
  
  modelString = paste(DV, "~ DASS_depression_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[3,] <- summary(mod1)$coefficients[2,1:4]
  
  modelString = paste(DV, "~ SSMS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[4,] <- summary(mod1)$coefficients[2,1:4]
  
  modelString = paste(DV, "~ UPPS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[5,] <- summary(mod1)$coefficients[2,1:4]
  
  modelString = paste(DV, "~ AUDIT_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[6,] <- summary(mod1)$coefficients[2,1:4]
  
  modelString = paste(DV, "~ LSAS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[7,] <- summary(mod1)$coefficients[2,1:4]
  
  modelString = paste(DV, "~ OCIR_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[8,] <- summary(mod1)$coefficients[2,1:4]
  
  modelString = paste(DV, "~ AES_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[9,] <- summary(mod1)$coefficients[2,1:4]
  
  modelString = paste(DV, "~ EAT_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[10,] <- summary(mod1)$coefficients[2,1:4]
  
  plot1 <- data.frame(plot1)
  names(plot1) <- c("Estimate", "Std..Error", "t value", "P value")
  row.names(plot1) <- c("DASS Stress", "DASS Anxiety", "DASS Depression", "Schizotypy", "Impulsivity", "Alcoholism", "Social Anxiety", "OCD", "Apathy", "Eating Disorders")
  
  return(plot1)
}
```


```{r}
generic.model <- function(DV, df) {
  plot1 <- matrix(NA,10,4)
  modelString = paste(DV, "~ DASS_stress_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[1,] <- summary(mod1)$coefficients[2,1:4]

  modelString = paste(DV, "~ DASS_anxiety_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[2,] <- summary(mod1)$coefficients[2,1:4]

  modelString = paste(DV, "~ DASS_depression_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[3,] <- summary(mod1)$coefficients[2,1:4]

  modelString = paste(DV, "~ SSMS_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[4,] <- summary(mod1)$coefficients[2,1:4]

  modelString = paste(DV, "~ UPPS_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[5,] <- summary(mod1)$coefficients[2,1:4]

  modelString = paste(DV, "~ AUDIT_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[6,] <- summary(mod1)$coefficients[2,1:4]

  modelString = paste(DV, "~ LSAS_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[7,] <- summary(mod1)$coefficients[2,1:4]

  modelString = paste(DV, "~ OCIR_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[8,] <- summary(mod1)$coefficients[2,1:4]

  modelString = paste(DV, "~ AES_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[9,] <- summary(mod1)$coefficients[2,1:4]

  modelString = paste(DV, "~ EAT_ln_sc + NCS_ln_sc + Age_sc + Gender")
  mod1 <- lm(modelString, df)
  plot1[10,] <- summary(mod1)$coefficients[2,1:4]

  plot1 <- data.frame(plot1)
  names(plot1) <- c("Estimate", "Std..Error", "t value", "P value")
  row.names(plot1) <- c("DASS Stress", "DASS Anxiety", "DASS Depression", "Schizotypy", "Impulsivity", "Alcoholism", "Social Anxiety", "OCD", "Apathy", "Eating Disorders")

  return(plot1)
}

#Linear regressions for 
regAccuracyTrait <- generic.model("Correct_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Accuracy")
regConfidenceTrait <- generic.model("Confidence_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Confidence")
regIBdtbTrait <- generic.model("DTB_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "DTB")
regIBipTrait <- generic.model("Ipast_task_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ip_task")
regIBifTrait <- generic.model("Ifuture_task_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "If_task")
regIBipbothTrait <- generic.model("Ipast_both_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ip_both")
regIBifbothTrait <- generic.model("Ifuture_both_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "If_both")
#regIBifratioTrait <- generic.model("ratio_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ifratio")
regIBipdiffTrait <- generic.model("pastdiff_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ip_diff")
regIBifdiffTrait <- generic.model("diff_sc", summedscaledData) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "If_diff")


regTrait_fig<-rbind(regAccuracyTrait,regConfidenceTrait,
                    regIBdtbTrait,
                    regIBipTrait,regIBifTrait,
                    regIBipbothTrait,regIBifbothTrait,
                    #regIBifratioTrait,
                    regIBipdiffTrait,regIBifdiffTrait)
regTrait_fig$Label<-factor(regTrait_fig$Label, levels=c("Accuracy",'Confidence',
                                                      "DTB",
                                                      "Ip_task","If_task",
                                                      "Ip_both","If_both",
                                                      #"Ifratio",
                                                      "Ip_diff","If_diff"))
regTrait_fig$Type<-factor(regTrait_fig$Type, levels=c("DASS Stress", "DASS Anxiety", "DASS Depression", "Schizotypy", "Impulsivity", "Alcoholism", "Social Anxiety", "OCD", "Apathy", "Eating Disorders"))

# Plot: Task performance + Metacognition ~ Symptom Scores
regTrait <- ggplot(data = regTrait_fig, aes(x = Label, y = Estimate, group=Type)) +       
  geom_bar(aes(fill = Type), colour="black",size=1.2,stat="identity", position = "dodge",width=0.8) +
  geom_errorbar(aes(ymin=regTrait_fig$Estimate-regTrait_fig$Std..Error, ymax=regTrait_fig$Estimate+regTrait_fig$Std..Error),colour="black", width=0.3, size=1.2, position=position_dodge(.8)) +
  geom_hline(yintercept=0,size=1) + theme_classic() + labs(title=" ", x=" ", y = "Regression Coefficient") +
  theme(axis.title.y = element_text(size = 18, angle = 90, margin=margin(0,20,0,0)), axis.title.x = element_text(size = 18, angle = 00, margin=margin(20,0,0,0)))+
  theme(plot.title = element_text(size = 18, angle = 00),legend.text = element_text(size = 18),legend.title = element_blank()) +
  theme(axis.text.x = element_text(angle = 00, size=18), axis.text.y = element_text(angle = 00, size=18))+ scale_x_discrete(expand = c(0,0.5)) +
  theme(axis.line.x = element_line(color="black", size = 1.2), axis.line.y = element_line(color="black", size = 1.2)) +
  theme(axis.ticks.y=element_line(size=(1.5)), axis.ticks.x=element_line(size=(1.5)), axis.ticks.length=unit(0.4, "cm")) +
  scale_fill_manual(values=c("#999999", "#377db8","#e31a1c","#984ea3","#4daf4a","#f781bf",'#ffff33','#ff7f00','#a65628','#ffffff'))#+ ylim(-0.3,0.4)

regTrait


#pdf("~/Documents/PennMed/Gold Lab/Lab Meeting 10122021/Figs/traitFig.pdf", width = 14, height = 4)
#regTrait
#dev.off()

#pdf("~/Documents/PennMed/Gold Lab/Grant/FigsforGrant/traitFig.pdf", width = 20, height = 4)
regTrait
#dev.off()
```


```{r}
# numrep = 1
# numsub = 14
# simqData <- do.call("rbind", replicate(numrep, qData, simplify = FALSE))
# simqData <- data.frame(lapply(simqData[,2:ncol(simqData)], jitter)) %>% dplyr::select(-contains("NCS"))
# simqSubjects <- paste0(rep(1:numrep, each = numsub), "_", replicate(numrep,qData$subject))
# het.mat <- hetcor(simqData)$cor

qData[!is.na(rowSums(qData[,2:ncol(qData)])),2:ncol(qData)] %>% colSums %>%as.data.frame() %>% set_colnames("sum") %>% ggplot(aes(x = sum)) + geom_bar()
qns = qData[,2:ncol(qData)] %>% dplyr::select(!contains("NCS"))
het.mat = hetcor(qns)$cor
```

```{r}
nCng(het.mat, cor = TRUE, model = "components", details = TRUE)
res <- nCng(het.mat, cor = TRUE, model = "components", details = TRUE)

#pdf("~/Documents/PennMed/Gold Lab/Preregistration/Urn-Confidence/UrnConfidenceQuestionnaire/Figs/CNG.pdf", width = 5, height = 5)
#pdf("~/Documents/PennMed/Gold Lab/Lab Meeting 10122021/Figs/CNG.pdf", width = 5, height = 5)
plotuScree(qData[,2:ncol(qData)], main=paste(res$nFactors,
                            " factors retained by the CNG procedure",
                            sep=""))
#dev.off()
```

```{r}
fa <- fa(r = het.mat, nfactors = 3, n.obs = nrow(simqData), rotate = "oblimin", fm="ml", scores="regression")
fa.scores <- factor.scores(x=qData[,2:ncol(qData)], f=fa)
scores = data.frame("subject"=qData$subject, fa.scores$scores)
loadings <- fa$loadings

factorDataV = merge(summedscaledData, scores, by.x=c("subject"), by.y=c("subject"))
```

```{r}
# linear regressions
regAccuracyFactor = lm(Correct_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV) # accuracy
regConfidenceFactor = lm(Confidence_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV)# mean confidence
regIBdtbFactor = lm(DTB_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV)
regIBipFactor = lm(Ipast_task_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV) 
regIBifFactor = lm(Ifuture_task_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV) 
regIBipbothFactor = lm(Ipast_both_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV) 
regIBifbothFactor = lm(Ifuture_both_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV) 
#regIBifratioFactor = lm(ratio_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV)
regIBipdiffFactor = lm(pastdiff_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV)
regIBifdiffFactor = lm(diff_sc ~ ML1 + ML2 + ML3 + NCS_ln_sc + Age_sc + Gender,factorDataV)

# extract coefficients into dataframes
regAccuracyFactor_fig <- data.frame(summary(regAccuracyFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Accuracy")
regConfidenceFactor_fig <- data.frame(summary(regConfidenceFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Confidence")
regIBdtbFactor_fig <- data.frame(summary(regIBdtbFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "DTB")
regIBipFactor_fig <- data.frame(summary(regIBipFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ip_task")
regIBifFactor_fig <- data.frame(summary(regIBifFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "If_task")
regIBipbothFactor_fig <- data.frame(summary(regIBipbothFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ip_both")
regIBifbothFactor_fig <- data.frame(summary(regIBifbothFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "If_both")
#regIBifratioFactor_fig <- data.frame(summary(regIBifratioFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ifratio")
regIBipdiffFactor_fig <- data.frame(summary(regIBipdiffFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "Ip_diff")
regIBifdiffFactor_fig <- data.frame(summary(regIBifdiffFactor)$coefficients[-1,]) %>% rownames_to_column(var = "Type") %>% dplyr::mutate(Label = "If_diff")

regFactor_fig <- rbind(regAccuracyFactor_fig,regConfidenceFactor_fig,
                       regIBdtbFactor_fig,
                       regIBipFactor_fig,regIBifFactor_fig,
                       regIBipbothFactor_fig,regIBifbothFactor_fig,
                       #regIBifratioFactor_fig,
                       regIBipdiffFactor_fig,regIBifdiffFactor_fig)
#regFactor_fig <- regFactor_fig[regFactor_fig$Type!='Gender',]
regFactor_fig <- regFactor_fig[grepl("ML",regFactor_fig$Type),]
#regFactor_fig$Type[regFactor_fig$Type=='iq.sc']<-'IQ'
regFactor_fig$Type[regFactor_fig$Type=='age.sc']<-'Age'
regFactor_fig$Label<-factor(regFactor_fig$Label, levels=c("Accuracy",'Confidence',
                                                      "DTB",
                                                      "Ip_task","If_task",
                                                      "Ip_both","If_both",
                                                      #"Ifratio",
                                                      "Ip_diff", "If_diff"))


# Plot: Task performance + Metacognition ~ Factors
factorFig <- ggplot(data = regFactor_fig, aes(x = Label, y = Estimate, group=Type)) +       
  geom_bar(aes(fill = Type), colour="black",size=1.2,stat="identity", position = "dodge",width=0.8) +
  geom_errorbar(aes(ymin=regFactor_fig$Estimate-regFactor_fig$Std..Error, ymax=regFactor_fig$Estimate+regFactor_fig$Std..Error),colour="black", width=0.3, size=1.2, position=position_dodge(.8))+
  geom_hline(yintercept=0,size=1) + theme_classic() + labs(title=" ", x=" ", y = "Regression Coefficient") +
  theme(axis.title.y = element_text(size = 18, angle = 90, margin=margin(0,20,0,0)), axis.title.x = element_text(size = 18, angle = 00, margin=margin(20,0,0,0)))+
  theme(plot.title = element_text(size = 18, angle = 00),legend.text = element_text(size = 18),legend.title = element_blank()) +
  theme(axis.text.x = element_text(angle = 00, size=18), axis.text.y = element_text(angle = 00, size=18))+ scale_x_discrete(expand = c(0,0.5)) +
  theme(axis.line.x = element_line(color="black", size = 1.2), axis.line.y = element_line(color="black", size = 1.2)) +
  theme(axis.ticks.y=element_line(size=(1.5)), axis.ticks.x=element_line(size=(1.5)), axis.ticks.length=unit(0.4, "cm")) #+
  #scale_fill_manual(values=c("#8dd3c7", "#ffffbc","#bebada")) + theme(legend.position="none") #+ ylim(-0.3,0.3)

factorFig

#pdf("~/Documents/PennMed/Gold Lab/Lab Meeting 10122021/Figs/factorFig.pdf", width = 10, height = 4)
#factorFig
#dev.off()

pdf("~/Documents/PennMed/Gold Lab/Grant/FigsforGrant/factorFig.pdf", width = 15, height = 4)
factorFig
dev.off()
```




```{r}
cbind(dplyr::select(factorDataV,contains("ML")),factorDataV[,c(2:12)]) %>% cor
```


```{r}
question_survey_map <- combinedData[,c('survey','variable')] %>% 
    #dplyr::mutate(variable = str_replace_all(variable, "-|#| ", ".")) %>%
    distinct()# %>%
    #dplyr::mutate(variable = ifelse(variable == "Q14", "AES", variable)) %>%

ld <- loadings[,] %>% reshape2::melt() %>% dplyr::rename("variable" = Var1, "factor" = Var2) %>% left_join(question_survey_map, by = "variable") 
```

```{r}
colorpalV <- data.table::fread("vickiecolorlist.csv") %>% as.data.frame()
surveycolors <- colorpalV$colorhex[1:11]
names(surveycolors) <- ld$survey %>% unique() %>% sort() %>% append("DASS")
f = "ML1"
ld_factor <- ld %>% #dplyr::filter(factor == f) %>%
    dplyr::mutate(survey = factor(survey,levels = unique(.$survey), ordered = T)) %>%
    dplyr::arrange(survey) %>%
    group_by(factor) %>%
    dplyr::mutate(ix = 1:180)

#pdf("~/Documents/PennMed/Gold Lab/Preregistration/Urn-Confidence/UrnConfidenceQuestionnaire/Figs/factorloadings_pilot.pdf", width = 11, height = 8)
#pdf("~/Documents/PennMed/Gold Lab/Lab Meeting 10122021/Figs/factorloadings.pdf", width = 14, height = 8)
ld_factor %>%
    ggplot() +       
    geom_bar(aes(x = ix, y = value, fill = survey), size=1.2,stat="identity", position = "dodge",width=0.8) +
    geom_hline(yintercept=0,size=1) + theme_classic() + labs(title=" ", x=" ", y = "Factor Loading") +
    theme(axis.title.y = element_text(size = rel(1.5), angle = 90, margin=margin(0,20,0,0)), axis.title.x = element_text(size = rel(1.5), angle = 00, margin=margin(20,0,0,0))) +
    theme(plot.title = element_text(size = rel(3), angle = 00),legend.text = element_text(size = rel(1)),legend.title = element_blank()) +
    theme(axis.text.x = element_blank(), axis.text.y = element_text(angle = 00))+ scale_x_discrete(expand = c(0,0.5)) +
    theme(axis.line.x = element_line(color="black", size = 1.2), axis.line.y = element_line(color="black", size = 1.2)) +
    theme(axis.ticks.y=element_line(size=(1.5)), axis.ticks.x=element_blank()) +
    scale_fill_manual(values = surveycolors) +
    facet_wrap(~factor, ncol = 1, strip.position = "right") + theme(text = element_text(size = 18)) 
#dev.off()

ld %>% #dplyr::filter(factor == f) %>%
    dplyr::mutate(survey = word(survey, sep = "_")) %>%
    dplyr::mutate(survey = factor(survey,levels = unique(.$survey), ordered = T)) %>%
    dplyr::arrange(survey) %>%
    group_by(factor, survey) %>%
    dplyr::summarise(total = sum(value)) %>% 
    ggplot() +       
    geom_bar(aes(x = survey, y = total, fill = survey), size=1.2,stat="identity", position = "dodge",width=0.8) +
    geom_hline(yintercept=0,size=1) + theme_classic() + labs(title=" ", x=" ", y = "Summed Factor Loading") +
    theme(axis.title.y = element_text(size = rel(1.5), angle = 90, margin=margin(0,20,0,0)), axis.title.x = element_text(size = rel(1.5), angle = 00, margin=margin(20,0,0,0))) +
    theme(plot.title = element_text(size = rel(3), angle = 00),legend.text = element_text(size = rel(1)),legend.title = element_blank()) +
    theme(axis.text.x = element_blank(), axis.text.y = element_text(angle = 00, size=18))+ scale_x_discrete(expand = c(0,0.5)) +
    theme(axis.line.x = element_line(color="black", size = 1.2), axis.line.y = element_line(color="black", size = 1.2)) +
    theme(axis.ticks.y=element_line(size=(1.5)), axis.ticks.x=element_blank()) +
    scale_fill_manual(values = surveycolors) +
    facet_wrap(~factor, ncol = 1, strip.position = "right") + theme(text = element_text(size = 18)) 
```


